# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Song"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://songbuild00.github.io/"
tags = []
features = []
min_version = "0.83.0"

[author]
  name = "Peter Song"
  homepage = "https://github.com/songbuild00/"

# If porting an existing theme
[original]
  name = "PaperMod"
  author = "Aditya Telange"
  homepage = "https://github.com/adityatelange/"
  repo = "https://github.com/adityatelange/hugo-PaperMod/"
